/**
 * jojo's design tokens, transcribed from `web/src/index.css`.
 *
 * The web app treats that file as the single source of design truth, and the
 * two palettes below are the same hex values it ships — measured for WCAG
 * contrast on the surfaces they land on, and validated for colour-blind
 * separation across the six pipeline stages. Retheming the whole mobile app
 * means editing the two blocks here and nothing else.
 *
 * What deliberately did NOT come across: the shadcn variable indirection
 * (`--color-primary` → `--accent`), which exists so third-party web components
 * inherit the theme. Nothing here is generated by a CLI, so the aliases would
 * be two names for one colour with no second reader.
 */

export type ThemeName = 'light' | 'dark'

export type Palette = {
  /* Surfaces, darkest to lightest in both themes — see the note in index.css
     about the dark ramp having been upside down. */
  page: string
  panel: string
  well: string
  raised: string
  hairline: string
  hairlineStrong: string
  rowHover: string

  /* Text ramp */
  text1: string
  text2: string
  text3: string

  /* Accent — monochrome, per shadcn: near-black light, near-white dark */
  accent: string
  accentFg: string
  accentSoft: string
  accentBorder: string

  /* Info — a soft brand colour for data that is not a status */
  info: string
  infoSoft: string
  infoBorder: string

  /* Status. Reserved: never reused as a chart series. */
  danger: string
  dangerSoft: string
  dangerBorder: string
  warning: string
  warningSoft: string
  warningBorder: string
  success: string
  successSoft: string
  successBorder: string

  /* Chart series — a separate namespace from status, so a red segment is
     never ambiguous between "overdue" and "series 4". */
  series: [string, string, string, string, string]

  /* Sequential ramp for shares of a total (the donut, the outcomes bar) */
  ramp: [string, string, string, string]

  /* Pipeline stages. Neither status nor chart series: they must stay
     separable at 6px on the `well` track. */
  stage: {
    draft: string
    submitted: string
    screen: string
    interview: string
    offer: string
    closed: string
  }

  /** The wash behind a modal sheet. */
  scrim: string
}

export const LIGHT: Palette = {
  page: '#f5f5f5',
  panel: '#ffffff',
  well: '#f5f5f5',
  raised: '#ffffff',
  hairline: '#e5e5e5',
  hairlineStrong: '#b5b5b5',
  rowHover: '#f0f0f0',

  text1: '#0a0a0a',
  text2: '#525252',
  text3: '#696969',

  accent: '#171717',
  accentFg: '#fafafa',
  accentSoft: '#ebebeb',
  accentBorder: '#a3a3a3',

  info: '#3b6fbf',
  infoSoft: '#eff4fc',
  infoBorder: '#cbdcf3',

  danger: '#c81e1e',
  dangerSoft: '#fef2f2',
  dangerBorder: '#fecaca',
  warning: '#a16207',
  warningSoft: '#fefce8',
  warningBorder: '#fde68a',
  success: '#15803d',
  successSoft: '#f0fdf4',
  successBorder: '#bbf7d0',

  series: ['#4f9dc9', '#c96b64', '#cea441', '#449970', '#8a6bbf'],
  ramp: ['#2f6f97', '#4f9dc9', '#86bcdb', '#c2dcec'],

  stage: {
    draft: '#737373',
    submitted: '#3c92c3',
    screen: '#aa842c',
    interview: '#8a6bbf',
    offer: '#449970',
    closed: '#c96b64',
  },

  scrim: 'rgba(10, 10, 10, 0.45)',
}

export const DARK: Palette = {
  page: '#0a0a0a',
  panel: '#1f1f1f',
  well: '#171717',
  raised: '#1f1f1f',
  hairline: '#333333',
  hairlineStrong: '#4a4a4a',
  rowHover: '#2a2a2a',

  text1: '#fafafa',
  text2: '#d4d4d4',
  text3: '#a1a1a1',

  accent: '#fafafa',
  accentFg: '#171717',
  accentSoft: '#303030',
  accentBorder: '#5a5a5a',

  info: '#7ba5e8',
  infoSoft: '#16202e',
  infoBorder: '#2a3c55',

  danger: '#ff6467',
  dangerSoft: '#2a1515',
  dangerBorder: '#4a2020',
  warning: '#fbbf24',
  warningSoft: '#262010',
  warningBorder: '#453714',
  success: '#4ade80',
  successSoft: '#12241a',
  successBorder: '#1e4030',

  series: ['#3e96c6', '#cf6a62', '#b18d39', '#45a075', '#9d84d4'],
  ramp: ['#8ec4e2', '#4f9dc9', '#3a7ba3', '#2a5975'],

  stage: {
    draft: '#a1a1a1',
    submitted: '#3e96c6',
    screen: '#b18d39',
    interview: '#9d84d4',
    offer: '#45a075',
    closed: '#cf6a62',
  },

  scrim: 'rgba(0, 0, 0, 0.62)',
}

export const PALETTES: Record<ThemeName, Palette> = { light: LIGHT, dark: DARK }

/**
 * The type scale, one step up from the web's.
 *
 * The web app sets body at 14px and table rows at 13px, which is right for a
 * pointer at arm's length and too tight in the hand. Every step is nudged by a
 * point or two; the *ratios* are unchanged, so the hierarchy reads identically.
 */
export const type = {
  xs: 12,
  sm: 13,
  base: 15,
  md: 16,
  lg: 17,
  xl: 22,
  xxl: 30,
} as const

export const lineHeight = {
  xs: 16,
  sm: 19,
  base: 22,
  md: 23,
  lg: 24,
  xl: 28,
  xxl: 34,
} as const

/** 4px grid, the same rhythm the web app's Tailwind spacing sits on. */
export const space = {
  0.5: 2,
  1: 4,
  1.5: 6,
  2: 8,
  2.5: 10,
  3: 12,
  3.5: 14,
  4: 16,
  5: 20,
  6: 24,
  8: 32,
  10: 40,
  12: 48,
} as const

export const radius = { sm: 6, md: 8, lg: 12, xl: 16, full: 999 } as const

/**
 * 44pt is the floor for anything a finger lands on. The web app spends a whole
 * `@media (pointer: coarse)` block reaching this with invisible catch areas
 * around 28px buttons; on a platform where everything is touch, controls are
 * simply drawn at the size they need to be.
 */
export const TAP = 44

/**
 * These five strings are each font's PostScript name, and that is the only shape
 * both platforms agree on. Android matches `fontFamily` against the asset
 * filename, so the five TTFs were renamed to match; iOS matches against a family
 * name first and falls back to `UIFont(name:)`, which takes a PostScript name.
 *
 * The obvious alternative — `fontFamily: 'Inter'` plus `fontWeight` — is wrong
 * for these particular files, and it was measured rather than assumed. Only
 * Regular and Bold carry the family name `Inter`; Medium and SemiBold declare
 * themselves as the families `Inter Medium` and `Inter SemiBold`. Asking for
 * `Inter` at weight 500 makes RCTFontWithFontProperties pick the nearest weight
 * in the `Inter` family, which is Bold. Medium and SemiBold would silently
 * render one and two steps too heavy.
 */
export const fonts = {
  regular: 'Inter-Regular',
  medium: 'Inter-Medium',
  semibold: 'Inter-SemiBold',
  bold: 'Inter-Bold',
  mono: 'JetBrainsMono-Regular',
} as const
